### PR TITLE
add 2x I/O commands

### PR DESCRIPTION
**Pull request by ampotos**
added support for 2x I/O commands

### CODE REVIEW

**Comment by alainiamburg** [comment]
hi ampotos, thanks for the contribution! I appreciate it.

One question though, why did you add lines 199,200 and 252? Technically there is a "No-Op" command 0x00, but anyway I wondered if there was an underlying reason. If not, would you mind re submitting without those lines? Thanks!

**Comment by ampotos** [comment]
I think it's testing code I forgot to remove. It should be fine now.

**Comment by alainiamburg** [comment]
I also see lines 366-368 were removed... this was for printing "unknown command" if verbosity is > 0... was that also something you added during testing? :)

**Comment by ampotos** [comment]
Yes sorry, it's fixed

**Comment by alainiamburg** [comment]
Thank you!

**Pull request merged**
